run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - gocritic
    - unused
    - ineffassign
    - revive
    - typecheck
    - gosimple
    - bodyclose

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
